version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    depends_on:
      - app
    links:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/app/${DOCKERFILE_NAME}
      args:
        UID: ${UID}
        GID: ${GID}
    command: ['php-fpm', '--nodaemonize']
    working_dir: /var/www/app
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/app
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1001}